CREATE TABLE pokemon_type (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE pokemon (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  type INTEGER NOT NULL REFERENCES pokemon_type(id) ON DELETE CASCADE,
  image TEXT,
  power INTEGER NOT NULL CHECK (power BETWEEN 10 AND 100),
  life INTEGER NOT NULL CHECK (life BETWEEN 10 AND 100)
);

CREATE TABLE weakness (
  id SERIAL PRIMARY KEY,
  type1 INTEGER NOT NULL REFERENCES pokemon_type(id) ON DELETE CASCADE,
  type2 INTEGER NOT NULL REFERENCES pokemon_type(id) ON DELETE CASCADE,
  factor FLOAT NOT NULL
);

ALTER TABLE weakness ADD CONSTRAINT unique_type_pair UNIQUE (type1, type2);
